# Generated by Django 5.1.3 on 2024-11-29 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_review'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
    ]
