# Generated by Django 5.1.3 on 2024-11-30 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_coupon_owner_alter_coupon_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='coupon_icons/'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 31, 3, 10, 40, 354842)),
        ),
    ]
