# Generated by Django 5.1.3 on 2024-11-30 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_coupon_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='icon',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 31, 4, 19, 30, 893644)),
        ),
    ]
